# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Deploys theme to the website
on: workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: rsync deployment
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzrhu --delete
          path: src/
          remote_path: /var/www/html/wp-content/themes/transgression/
          remote_host: 164.90.254.59
          remote_port: 2222
          remote_user: transgression
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
